apiVersion: apps/v1
kind: Deployment
metadata:
  name: our-node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: our-node-app
  template:
    metadata:
      labels:
        app: our-node-app
    spec:
      containers:
        - name: our-node-app
          image: moodyeg/our-node-app
          ports:
            - containerPort: 5124
---
apiVersion: v1
kind: Service
metadata:
  name: our-node-app-service
spec:
  type: NodePort
  selector:
    app: our-node-app
  ports:
    - protocol: TCP
      port: 5124
      targetPort: 5124
      nodePort: 30000
